### ISSUE TITLE
add-on won't install

### ISSUE THREAD

**Issue by badaniels** [hassio-addons/addon-appdaemon2#5]
hi,

Not sure why but I can't get your repository to install appdaemon. I'm very much a newb to hassio and so I don't really understand the error messages, but below is a dump from my log from where it tried to install appdaemon.

Thanks in advance.

```
17-11-11 22:11:03 INFO (MainThread) [hassio.addons.git] Clone addon https://github.com/hassio-addons/addon-appdaemon repository
17-11-11 22:11:09 INFO (MainThread) [hassio.addons.git] Remove custom addon repository https://github.com/home-assistant/hassio-addons-example
17-11-11 22:11:10 INFO (MainThread) [hassio.addons] Load addons: 19 all - 1 new - 2 remove
17-11-11 22:11:16 INFO (MainThread) [hassio.addons.addon] Create Home-Assistant addon data folder /data/addons/data/7bffb3a1_appdaemon
17-11-11 22:11:16 INFO (SyncWorker_11) [hassio.dock.addon] Start build 7bffb3a1/armhf-addon-appdaemon:dev
17-11-11 22:11:19 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 416, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 323, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/util.py", line 31, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/addons/addon.py", line 474, in install
    if not await self.docker.install(self.last_version):
  File "/usr/lib/python3.6/site-packages/hassio/dock/util.py", line 18, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 219, in _install
    return self._build(tag)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 232, in _build
    image = self.docker.images.build(**build_env.get_docker_args(tag))
  File "/usr/lib/python3.6/site-packages/docker/models/images.py", line 175, in build
    raise BuildError(chunk['error'])
docker.errors.BuildError: Please provide a source image with `from` prior to commit
```

**Comment by frenck** [comment]
Seems like you added the wrong repository to your Hass.io installation.
Please check the installation instructions of the add-on.

You should have added `https://github.com/hassio-addons/repository`.

**Comment by badaniels** [comment]
Hi, 

Yeah sorry, realised about 2 hours after my comment but I couldn't delete the comment.

Thanks though.

**Comment by frenck** [comment]
No problem m8 👍
